### ISSUE TITLE
Bug: Constructor extra super call

### ISSUE THREAD

**Issue by renaun** [RandoriAS/randori-compiler#124]
AS3:

``` actionscript
package bug
{ 
public class BugM extends BugSuperTest
{
    public function BugM(textures:Array) {
        if (textures.length > 0)
            super(textures[0]);
        else
            throw new Error("Empty texture array");
    }
}
}
```

``` actionscript
package bug
{ 
public class BugSuperTest
{
    public function BugSuperTest(texture:Object) {
        // do something with texture
    }

}
}
```

The output JS snippet is:

``` javascript
bug.BugM = function(textures) {
    bug.BugSuperTest.call(this);
    if (textures.length > 0)
        bug.BugSuperTest.call(this, textures[0]);
    else
        throw new Error("Empty texture array", 0);
};
```

The first "bug.BugSuperTest.call(this);" should not be there. 

Not sure this means consideration should be taken to only call it if there is a super present and move the Randori logic of setting var's in the constructor to a new randori specific function that then is inlined at the top of each constructor. This new Randori specific method for setting var's would have the inlined call to call parent's methods.

**Comment by teotigraphix** [comment]
@renaun @labriola @rolandzwaga This looks ridiculous, this isn't really even correct in the AS3 spec, I'm not touching this until there is a consensus

**Comment by rolandzwaga** [comment]
Honestly, I don't see how that code isn't following the AS3 spec, can you point out where you come to this conclusion? Calling a super constructor conditionally doesn't seem that heretical to me. Which part seems ridiculous to you?

**Comment by teotigraphix** [comment]
well then I have to much Java in me, I thought constructor calls had to come first and were called implicitly if not explicitly. but maybe I am thinking a different language.

Still didn't answer his question about the inline randori stuff.

**Comment by rolandzwaga** [comment]
I don't really follow the whole inline thing, I'm hoping @labriola will be able to say something more sensible about this.

**Comment by teotigraphix** [comment]
I'm not fixing this right now. The amount of logic and traversal needed to deal with this crappy code is unreal. Might look at it when I have time but this is an edge case since its the constructor. Other super.foo() do not apply to this problem. So like I said, with this implemented a performance hit is going to happen because EVERY constructors body will need to be scanned.

**Comment by teotigraphix** [comment]
OR I remove the implicit constructor call, chicken and egg since we are dealing with javascript here

**Comment by rolandzwaga** [comment]
Sounds fair to me to be honest, hoping other will chime in.

**Comment by labriola** [comment]
okay so the way the flash compiler works is that it always autogens one _unless_ there is a super call somewhere else in the method hence, if you dont want super called you need to do something dumb (in flash) like this

if ( false )
  super.foo();

so that it doesnt generate its own

so, i agree its a bug. how bad is the fix?

**Comment by teotigraphix** [comment]
I can fix it, I have a nice little majic trick in the compiler that can switch to a buffer temporarily. This might be fixed in an hour or so.

**Comment by teotigraphix** [comment]
commit      e532dac
