### ISSUE TITLE
Bug: "is" operator doesn't have full path of class on right side

### ISSUE THREAD

**Issue by renaun** [RandoriAS/randori-compiler#99]
AS 3 Code (2 classes):
bug/BugD.as:

```
package bug
{ 
public class BugD
{       
    public function BugD() {    
        if (!this is BugE)
            isRoot = true;
    }

    public var isRoot:Boolean = false;
}
}
```

bug/BugE.as:

```
package bug
{ 
public class BugE extends BugD
{       
    public function BugE() {    
        super();
    }
}
}
```

Snippet of JS output:

```
bug.BugD = function() {
    this.isRoot = false;
    if (!this instanceof BugE)
        this.isRoot = true;
};
```

Should be:

```
bug.BugD = function() {
    this.isRoot = false;
    if (!this instanceof bug.BugE)
        this.isRoot = true;
};
```

**Comment by labriola** [comment]
Well, the compiler output is  bug... however, even if it compiled correctly, this isnt going to work. These constructs dont exist in javascript in the same way as action script... so we are now talking about emulating a different virtual machine instead of cross compiling a language. This is going to be a problem and I think the larger issue needs to be discussed at length

**Comment by labriola** [comment]
okay, once we fix the compiler issue, i think ii see a path to resolve my other concerns

**Comment by teotigraphix** [comment]
ah ok, it took me a second to see what was going on. So its not emitting the qualified name.

**Comment by teotigraphix** [comment]
commit 7349a90
